### ISSUE TITLE
Bug: pause time while still rendering doesn't work on Macs

### ISSUE THREAD

**Issue by CornuAmmonis** [compute-toys/compute.toys#19]
The ctrl+click keybinding is equivalent to right-clicking on a Mac, so the keybinding can't be used. Suggest changing it to alt-click

**Comment by wrightwriter** [comment]
okay, can do that

**Comment by wrightwriter** [comment]
https://github.com/compute-toys/compute.toys/pull/25
Removed it, should be closed.
