### ISSUE TITLE
FR: Support Open Graph protocol

### ISSUE THREAD

**Issue by slerpyyy** [compute-toys/compute.toys#22]
We should add [open graph](https://ogp.me/) meta tags to the website

The following tags should be added to the `<head>` of every page
```xml
<meta property="og:title" content="...">
<meta property="og:type" content="...">
<meta property="og:image" content="...">
<meta property="og:url" content="...">
<meta property="og:description" content="...">
<meta property="og:site_name" content="...">
```

This allows apps like Discord to generate previews for links to the website

**Comment by CornuAmmonis** [comment]
A note on this, discord uses Twitter meta tags for larger embedded images in addition to OG tags

**Comment by munrocket** [comment]
@slerpyyy do we have thumbnails in db?

**Comment by davidar** [comment]
yeah, that's where the images on the browse page come from
