### ISSUE TITLE
Error occurs when using as standalone editor 

### ISSUE THREAD

**Issue by mikeny07** [compute-toys/compute.toys#55]
Attempted to use the `compute.toy` as a standalone editor by following the steps described in the README file, which involved deleting the `pages` directory before starting the server. Unfortunately, this approach did not work. 

I then tried to resolve the issue by clearing the cache, which involved deleting the `.next` directory. However, even after doing this, I consistently encountered the following error:

```
Server Error
Error: useAuth must be used within an AuthProvider

This error happened while generating the page. Any console logs will be displayed in the terminal window.

Source
lib\db\serializeshader.ts (128:28) @ useShaderSerDe

  126 |     const atomGetter = useAtomGetter();
  127 | 
> 128 |     const { user } = useAuth();
      |                            ^
  129 | 
  130 |     /*
  131 |         We DO NOT want to use getters here, even though

Call Stack
MetadataEditor
components\editor\metadataeditor.tsx (53:43)
```
Could you please provide guidance on how to resolve this issue?

**Comment by munrocket** [comment]
@mikeny07 don't remove `pages` at all.
If you want support without connection to db make PR, should be easy to fix because it worked month ago.

**Comment by davidar** [comment]
The problem is that this condition evaluates to true now, which makes it attempt to connect to the database. It should be disabled somehow for the standalone editor

https://github.com/compute-toys/compute.toys/blob/master/components/editor/editor.tsx#L76
